[build]
  publish = "build" # Directory Netlify will serve after the build is done
  command = "npm run build" # Command to build your project

# Set up basic redirects (optional, if you have specific paths)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
